### PR TITLE
Tds

### PR DESCRIPTION
**Pull request by nsgocev**
Habitat version which Uses TDS as Item Serialization Provider and Deployment Mechanism

### CODE REVIEW

**Comment by dashkodo** [comment]
TDS is paid solution. Why we should move from free unicorn to paid TDS?

**Comment by akamburov** [comment]
This is an alternative, not a replacement. TDS has more users than Unicorn and provides advanced features.

We spoke with Thomas that there could be a TDS branch of Habitat which will be supported between releases/tags so developers who prefer TDS can use it instead.

**Comment by cassidydotdk** [comment]
How does this match up with the terms of contribution?

"Generally any requirements on 3rd party commercial software will not be approved
All parts of your contribution must be complete free of any licensing and free to distribute
We reserve the right to change the terms of contribution at any time"

**Comment by nsgocev** [comment]
As @akamburov stated. This is just an alternative. My local fork might remain the main Habitat TDS version. :)

**Comment by GoranHalvarsson** [comment]
How do you know that TDS has more users than Unicorn?

Br
Göran Halvarsson

**Comment by akamburov** [comment]
@nsgocev closed this request because it shouldn't be against the master. We were thinking of a branch that could be supported separately which won't violate the terms of contribution directly. As Nikola said, his fork could remain the Habitat TDS "version" if having a real branch is not workable/needed.

@GoranHalvarsson Just a hunch :) Anyway the idea is that some might prefer TDS because of various reasons so instead of them having to replace Unicorn, they can be provided with that option. A similar discussion was brought up in Slack regarding front-end frameworks and other components of the architecture.

**Comment by GoranHalvarsson** [comment]
Hello

Yes but great idea that you will have a TDS option for habitat.

You guys are doing a dam good job. :-)

Br
Göran Halvarsson

**Comment by murrayba** [comment]
Hi @nsgocev 

I'm unable to deploy using TDS, perhaps a newbie mistake or something missing from the install steps. I hope you can point me in the right direction...

The error is: "warning MSB3026: Could not copy "C:\Projects\Habitat-tds\src\Feature\Identity\tds\Sitecore.Feature.Identity.Master\bin\Debug\\bin\Sitecore.Kernel.dll" to "S:\inetpub\wwwroot\SXSitecoreDEV\Website\bin\Sitecore.Kernel.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'S:\inetpub\wwwroot\SXSitecoreDEV\Website\bin\Sitecore.Kernel.dll' because it is being used by another process.'

This seems sensible, I assume the kernel is used by TDS services so will be in use - but I can't just ignore the error because while all other DLL files are copied correctly, the database remains untouched, no new content. Any idea what I'm doing wrong?

**Comment by nsgocev** [comment]
Hi @murrayba !

The mistake is actualy on my end. The TDS projects were not set correctly to exclude Sitecore Assemblies. The mistake was fixed with commit 15fd549 (https://github.com/nsgocev/Habitat/commit/5778f5e2fe18eed555b19b42b3690a4992522767). Please get the latest version in the fork itself. 

As this version was tested to some extent - I was expecting bugs like these :) 

Thanks a lot for the valuable feedback !

**Comment by murrayba** [comment]
Thanks @nsgocev, all fixed :)

**Pull request closed without merging**
