### PR TITLE
Convert all projects from using packages.config over to project.json

### PR DESCRIPTION
**Pull request by kamsar**
This PR converts Habitat over to the project.json packaging format (as initially done by @SaintSkeeta in https://github.com/HedgehogDevelopment/Habitat/tree/TDS-Symposium2016-NuGet82).

Other minor changes required:
* Normalized framework version to 4.6 across all projects
* Fixed Foundation.Testing not actually referring to the MVC NuGet package
* Added NuGet.config to point to the Sitecore Public NuGet feed automatically
* Updated .gitignore to exclude apropos files

Done with PowerShell :)

### CODE REVIEW

**Comment by SaintSkeeta** [comment]
I've recently found that the WFFM packages aren't currently public.... So my local was working because of packages I had generated locally a while back.
I suggest holding off until they show up in the public feed.

**Comment by kamsar** [comment]
Yeah there are no references to WFFM packages in the project.json due to that very reason. Those are still pointed to local assemblies.

But yes those ought to get on the feed :)

**Comment by kamsar** [comment]
There's also the issue, as @SaintSkeeta mentioned in the Slack channel, of package compatibility.

As soon as you go to NuGet 3/project.json, you lose the ability to have packages deploy solution items. I gather this is because MS likes to throw the baby out with the bathwater.

As examples, SimpleInjector could not deploy its startup class. Unicorn could not deploy its config files. They could be deployed manually but it's a lot uglier than v2 for that. Even though dependency management is a lot nicer.

**Comment by Eldblom** [comment]
There seem to be a ton of compiler warnings due to inconsistent assembly versions. Also the unit tests does not run on my local build.

**Comment by Eldblom** [comment]
Abandoning v3 feed for now, sticking with v2 support

**Pull request closed without merging**
