### PR TITLE
Feature/events

### PR DESCRIPTION
**Pull request by Azadehkhojandi**
Events Feature
Events feature is added to sitecore habitat website. This feature lets content editors create events in sitecore backend. It gives the ability to content editors to add calendar module on any page to display events in calendar or add link to list of events page. Each event has it’s own detail page. On event detail page web site visitors can see venue of the event on Google Maps and they would be able to the event into their calendar (icalendar, google calendar, outlook. outlook online, yahoo calendar).  All of renderings are responsive.
This feature also helps web site marketers and events organisers  to see popular events and analyse interest on each event based on number of people add the event in their calendar.

How to install it:

1- Install the Event feature module
2- Open sitecore content editor and go to /sitecore/content/Habitat/Home/Modules/Feature/Events
3- Add Events
4- Publish added Events
5- List of events page {your site}/Modules/Feature/Events
6- Event page {your site}/Modules/Feature/Events/{item bucket categories}/{event name}
7- Add Google Maps API key in the Root node settings to see maps on event detail page
8- You can add calendar with content editor to any page 
for example let’s add it to home page
	8-1 goto habitat homepage
	8-2 click on presentation detail
	8-3 add event calendar rendering - set data source pointing to /sitecore/content/Habitat/Home/Modules/Feature/Events

### CODE REVIEW

**Comment by Azadehkhojandi** [comment]
Videos:
Intro part 1 - https://youtu.be/abs7W2kKTHs
Intro part 2 - https://youtu.be/j0Fi62Zw_xQ

Contributes:
Azadeh Khojandi
Sudeep Shakya

**Comment by Azadehkhojandi** [comment]
Videos:
Intro part 1 - https://youtu.be/abs7W2kKTHs
Intro part 2 - https://youtu.be/j0Fi62Zw_xQ

Contributes:
Azadeh Khojandi
Sudeep Shakya

**Comment by Eldblom** [comment]
Thanks for your pull request @Azadehkhojandi. Please be patient as we asses the module for integration into Habitat.

**Comment by Eldblom** [comment]
Saved this in a local feature branch - still to be merged. Closing this PR

**Pull request closed without merging**
