### PR TITLE
[#422] Fixes for PackageReference conversion

### PR DESCRIPTION
**Pull request by nickwesselman**
* update mechanism of restoring nuget packages to avoid finding wrong MSBuild
* Fix System.Web.Mvc references on some test projects to PackageReference

### CODE REVIEW

**Comment by derekcorreia** [comment]
Pulling and testing

**Comment by derekcorreia** [comment]
Gets further. Restore works properly (or appears to).

Full gist of a run here: https://gist.github.com/derekcorreia/950062cf17ab39f4a3d3a7a7187eefef

Many reference missing or mismatched errors like the following:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime.Extensions" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding> [C:\projects\Habitat\src\Foundation\DependencyInjection\code\Sitecore.Foundation.DependencyInjection.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\projects\Habitat\src\Foundation\Installer\code\Sitecore.Foundation.Installer.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\Habitat\src\Foundation\Testing\tests\Sitecore.Foundation.Testing.csproj]
```

Ends with following error:
```
[15:01:19] MSBuild failed with code 1!
[15:01:19] 'Build-Solution' errored after 2.48 min
[15:01:19] Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\projects\Habitat\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[15:01:19] 'default' errored after 2.58 min
[15:01:19] Error in plugin 'run-sequence(Build-Solution)'
Message:
    MSBuild failed with code 1!
Stack:
Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\projects\Habitat\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[15:01:19] 'Publish-All-Projects' errored after 2.48 min
[15:01:19] Error in plugin 'run-sequence(default)'
Message:
    MSBuild failed with code 1!
Stack:
Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\projects\Habitat\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[15:01:19] 'Publish-All-Projects' errored after 2.48 min
[15:01:19] Error in plugin 'run-sequence(Build-Solution)'
Message:
    MSBuild failed with code 1!
Stack:
Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\projects\Habitat\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by nickwesselman** [comment]
Those warnings should be OK, but looks like there are still some MVC references in here that assume a `packages` folder. Must have been references added w/out nuget dependency. Why it builds OK for me, who knows. But I'll fix.

**Comment by nickwesselman** [comment]
@derekcorreia Please try again when you have a minute.

**Comment by nickwesselman** [comment]
I ran a couple clean builds and I think things are good now, going to merge this in case others are trying to build. @derekcorreia I'll keep your issue #422 open in case it needs more work.

**Pull request merged**
