### PR TITLE
Use Nuget Latest version of Unicorn and remove assemblies from lib folder

### PR DESCRIPTION
**Pull request by yalahyane**

### CODE REVIEW

**Comment by yalahyane** [comment]
@Eldblom Hi, Thomas, Can you please check and approve this PR?

**Comment by Eldblom** [comment]
Unicorn.Roles and Unicorn.Users was missing from the Foundation.Accounts project.
Added the 3.3.0 version and re-serialized

**Comment by Eldblom** [comment]
Please note that if this PR is merged, PR #15 in Sitecore.Demo needs to be merged too

**Comment by Eldblom** [comment]
Just found out that the re-serialization introduced an old favorite: If a checkbox field is "blank" as in "unchecked", Unicorn will remove the field from the serialization - and the field will fall back to its standard value, which might be "checked".
**Please do not merge until fixed**

**Pull request closed without merging**
