### PR TITLE
Update to Sitecore 8.2 Update 1

### PR DESCRIPTION
**Pull request by bplasmeijer**
Making the solution work with Sitecore 8.2 update 1
Update references and csproj files

### CODE REVIEW

**Comment by sergeyshushlyapin** [comment]
Please do not forget to update [FakeDb](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/pull/149).

**Comment by bplasmeijer** [comment]
@sergeyshushlyapin locally successfully ... cannot see build fault

**Comment by Eldblom** [comment]
@yassinealahyane Can this be closed?

**Comment by yassinealahyane** [comment]
Yes. We don't need to merge it. Update 1 is already merged...
Thanks.

**Pull request closed without merging**
