### PR TITLE
Extracted installer from website to separate module

### PR DESCRIPTION
**Pull request by dashkodo**

### CODE REVIEW

**Comment by Eldblom** [comment]
Please revise the name. What is the purpose of the module? Infrastructure is not a purpose. Maybe Framework.ConfigTransform?

**Comment by dashkodo** [comment]
I think Framework.Installer has more sense

**Comment by Eldblom** [comment]
Installer sounds good

**Comment by Eldblom** [comment]
OR maybe Framework.ContinuousIntegration? This has to do with auto deployment, right?

**Comment by dashkodo** [comment]
Not only CI, we may want distribute habitat as Sitecore package.

**Comment by Eldblom** [comment]
Framework.Installer it is... :)

**Pull request merged**
