### PR TITLE
Simplify Unicorn sync script

### PR DESCRIPTION
**Pull request by kamsar**
All that config file parsing wasn't needed since there's a shortcut to
say sync all.

Also merged latest sync scripts from 3.1.6 (works with earlier versions
too)

### CODE REVIEW

**Comment by Eldblom** [comment]
But the order of execution is critical. In previous versions the sync all operation was merely in order of configuration, not by dependencies. Has this changed in the latest?

Best Regards,
Thomas Eldblom

**Comment by kamsar** [comment]
All forms of sync resolve configs by dependency order. See https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/ControlPanel/ControlPanelUtility.cs#L70

**Comment by stasmaxymov** [comment]
Looks like there is no ordering when queryParameter is empty:
https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/ControlPanel/ControlPanelUtility.cs#L64

**Comment by kamsar** [comment]
Well that is silly. I'll fix it.

**Comment by kamsar** [comment]
Unicorn is now upgraded to 3.1.7 in this branch, which orders 'sync all' by dependency order correctly. Ref: https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/ControlPanel/ControlPanelUtility.cs#L74

**Pull request merged**
